export const dom = {
  viewer: document.getElementById('viewer'),
  fileInput: document.getElementById('fileInput'),
  exportBtn: document.getElementById('exportBtn'),
  toPdfModeBtn: document.getElementById('toPdfModeBtn'),
  backToSelectBtn: document.getElementById('backToSelectBtn'),
  exportPdfBtn: document.getElementById('exportPdfBtn'),
  editorRoot: document.getElementById('editorRoot'),
  selectionRoot: document.getElementById('selectionRoot'),
  pdfSidebar: document.getElementById('pdfSidebar'),
  selectionPanel: document.getElementById('selectionPanel'),
  pdfList: document.getElementById('pdfList'),
  dummyPdfInner: document.getElementById('dummyPdfInner'),
  dummyPdfViewport: document.getElementById('dummyPdfViewport'),
  zoomRange: document.getElementById('zoomRange'),
  addPageBtn: document.getElementById('addPageBtn'),
  prevPageBtn: document.getElementById('prevPageBtn'),
  nextPageBtn: document.getElementById('nextPageBtn'),
  busyOverlay: document.getElementById('busyOverlay'),
  busyMessage: document.getElementById('busyMessage')
};
